### ISSUE TITLE
Editing/Adding Partners doesn't work

### ISSUE THREAD

**Issue by CatalystNW** [CatalystNW/AVT#6]
We are unable to add or edit current partners.

Under the Projects module
a) Click on a project
b) Click on the Partners tab
c) Click on Modify Partners
From here you can edit or try to create a partner, but it never completes when you click "Save" on the popup window.

**Comment by CatalystNW** [comment]
Ability to edit Parners is restored.  Creating new ones still is bugged as it will create a blank Partner.  Work a round is to create a blank one then edit it with corrections.

**Comment by JJMilmore** [comment]
We resolved this in 2022 summer.
